version: '3.8'
#启动命令 docker compose -p nexus-stack -f docker-compose-mid.yml up -d
services:
  nexus-stack-admin:
    build:
      context: service/admin
    image: nexus-stackprd/-admin-service:1.0-SNAPSHOT
    container_name: nexus-stack-admin-prd
    ports:
      - "18081:18081"
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器1内网ip/你的虚拟机1内网ip
    networks:
      nexus-stack_network_prd:
  nexus-stack-file:
    build:
      context: service/file
    ports:
      - "18082:18082"
    image: nexus-stackprd/-file-service:1.0-SNAPSHOT
    container_name: nexus-stack-file-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器1内网ip/你的虚拟机1内网ip
    networks:
      nexus-stack_network_prd:
  nexus-stack-gateway:
    build:
      context: service/gateway
    ports:
      - "18080:18080"
    image: nexus-stackprd/-gateway-service:1.0-SNAPSHOT
    container_name: nexus-stack-gateway-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器1内网ip/你的虚拟机1内网ip
    networks:
      nexus-stack_network_prd:
  nexus-stack-portal:
    build:
      context: service/portal
    ports:
      - "18083:18083"
    image: nexus-stackprd/-portal-service:1.0-SNAPSHOT
    container_name: nexus-stack-portal-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器1内网ip/你的虚拟机1内网ip
    networks:
      nexus-stack_network_prd:
networks:
  nexus-stack_network_prd:
