spring:
  application:
    name: wisp-code
  profiles:
    active: ${RUN_ENV}
  main:
    web-application-type: reactive
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      #base-url: https://ws-jif4zqqb15c1hesv.cn-beijing.maas.aliyuncs.com/compatible-mode/v1/chat/completions
      chat:
        options:
          model: deepseek-v4-pro-0813
          temperature: 0.7
    vectorstore: # 本地运行先关闭 milvus bean 的创建
      milvus:
        enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.160.131:3306/wispcode?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bitedev
    password: bite@123

management:
  health:
    redis:
      enabled: false