spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frameworkjava_admin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bitedev
    password: bite@123
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info